spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://note-mysql:3306/flash-note?useUnicode=true&characterEncoding=UTF-8&serverTimezone=GMT%2B8&autoReconnect=true
    username: root
    password: 123456
  redis:
    host: note-redis
    port: 6379
  rabbitmq:
    host: note-rabbitmq
    port: 5672
    username: pika
    password: pika
    virtual-host: flashnote


server:
  port: 9900